# Generated by Django 3.1.1 on 2020-09-29 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
        ('review', '0002_reviewmodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beer.beer'),
        ),
    ]
