# Generated by Django 3.1.1 on 2020-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_reviewmodel_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='beer_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
