# Generated by Django 3.1.1 on 2020-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewmodel_beer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='author_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
