# Generated by Django 3.1.1 on 2020-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_kr', models.CharField(max_length=100, null=True)),
                ('style', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('abv', models.FloatField(default=0, null=True)),
            ],
            options={
                'db_table': 'beer',
            },
        ),
    ]
