# Generated by Django 3.1.1 on 2020-09-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
