# Generated by Django 3.1.1 on 2020-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0004_auto_20200929_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
